### ISSUE TITLE
did you skid a hypixel client into beta 1.1

### ISSUE THREAD

**Issue by FluorideHistorian** [Ihaveatrashaim/Beta-1.1_02-Cheat#1]
mc.thePlayer.motionY = 0;
mc.thePlayer.motionY *= 0;

**Comment by Ihaveatrashaim** [comment]
Right right. I don't know if is this supposed to be a joke or not. But may I ask who the heck in the world would bother to spend their time to skid 2 lines of code? You say this is like you taking an exam. There is a question you clearly know the answer is A but you have to choose B because other dude already choose A. I would not spending my time just to skid 2 line of code.
